const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {PDFDocument}=require('./dist/vendor/pdf-lib.min.js');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage();await page.goto('http://127.0.0.1:4173');await page.waitForFunction(()=>window.PDFLib);
 await page.evaluate(()=>{window.seenLoading=[];new MutationObserver(()=>{if(!document.querySelector('#loading-panel').hidden)window.seenLoading.push({stage:document.querySelector('#loading-label').textContent,value:document.querySelector('#loading-bar').getAttribute('aria-valuenow')});}).observe(document.querySelector('#loading-panel'),{subtree:true,attributes:true,childList:true});});
 const pdf=await PDFDocument.create();pdf.addPage();pdf.addPage();await page.locator('#pdf-input').setInputFiles({name:'progress.pdf',mimeType:'application/pdf',buffer:Buffer.from(await pdf.save())});await page.waitForFunction(()=>document.querySelector('#page-label').textContent==='1 / 2'&&!document.querySelector('#pdf-input').disabled);
 const seen=await page.evaluate(()=>window.seenLoading);for(const stage of ['1 / 3','2 / 3','3 / 3'])if(!seen.some(s=>s.stage.startsWith(stage)))throw Error('Missing stage '+stage);if(seen.some(s=>!s.stage.startsWith('1 / 3')&&s.value!==null))throw Error('Invented percentage');if(await page.locator('#loading-panel').isVisible())throw Error('Progress not dismissed');
 await page.locator('#next').click();await page.waitForFunction(()=>document.querySelector('#page-label').textContent==='2 / 2'&&!document.querySelector('#pdf-input').disabled);if(!(await page.evaluate(()=>window.seenLoading)).some(s=>s.stage==='正在顯示頁面'))throw Error('No page progress');
 await page.locator('#pdf-input').setInputFiles({name:'invalid.pdf',mimeType:'application/pdf',buffer:Buffer.from('invalid')});await page.waitForFunction(()=>document.querySelector('#status').classList.contains('error'));if(await page.locator('#loading-panel').isVisible()||await page.locator('#pdf-input').isDisabled())throw Error('Error recovery blocked');console.log('PASS: loading phases, determinate/indeterminate semantics, page navigation, completion and error cleanup.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
