const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {PDFDocument,degrees}=require('./dist/vendor/pdf-lib.min.js');const fs=require('fs');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4173');await page.waitForFunction(()=>window.PDFLib);
 const doc=await PDFDocument.create();for(const angle of [0,90,180,270]){const p=doc.addPage([600,800]);p.setCropBox(30,40,530,700);p.setRotation(degrees(angle));}
 const file={name:'ink.pdf',mimeType:'application/pdf',buffer:Buffer.from(await doc.save())};await page.locator('#pdf-input').setInputFiles(file);await page.waitForFunction(()=>!document.querySelector('#pen-toggle').disabled);await page.locator('#pen-toggle').click();
 await page.locator('#pen-color').fill('#ee1111');await page.locator('#pen-width').fill('8');await page.locator('#pen-width').dispatchEvent('input');
 for(let n=1;n<=4;n++){const r=await page.locator('#ink').boundingBox();await page.mouse.move(r.x+r.width*.2,r.y+r.height*.2);await page.mouse.down();await page.mouse.move(r.x+r.width*.3,r.y+r.height*.3,{steps:8});await page.mouse.move(r.x+r.width*.45,r.y+r.height*.15,{steps:8});await page.mouse.up();if(n<4){await page.locator('#next').click();await page.waitForFunction(n=>document.querySelector('#page-label').textContent===`${n+1} / 4`&&!document.querySelector('#pen-toggle').disabled,n);}}
 await page.locator('#ink-undo').click();if(await page.locator('#ink path').count())throw Error('undo failed');await page.locator('#ink-redo').click();if(await page.locator('#ink path').count()!==1)throw Error('redo failed');
 async function download(name){const [dl]=await Promise.all([page.waitForEvent('download'),page.locator('#download').click()]);await dl.saveAs(name);return [...fs.readFileSync(name)];}
 const bytes=await download('test-output/ink-only.pdf');
 await page.evaluate(async bytes=>{const pdfjs=await import('./vendor/pdf.mjs');const pdf=await pdfjs.getDocument({data:new Uint8Array(bytes)}).promise;for(let n=1;n<=4;n++){const p=await pdf.getPage(n),v=p.getViewport({scale:1}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;const ctx=c.getContext('2d');await p.render({canvasContext:ctx,viewport:v}).promise;for(const [nx,ny] of [[.2,.2],[.3,.3],[.45,.15]]){const x=ctx.getImageData(Math.round(nx*v.width),Math.round(ny*v.height),1,1).data;if(x[0]<190||x[1]>70||x[2]>70)throw Error('exported color or coordinates failed on page '+n);}const x=ctx.getImageData(Math.round(.2*v.width+12),Math.round(.2*v.height-12),1,1).data;if(x[0]<240||x[1]<240)throw Error('unexpected stroke thickness');}},bytes);
 await page.locator('#pen-toggle').click();const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=60;c.height=20;const x=c.getContext('2d');x.fillStyle='blue';x.fillRect(0,0,60,20);return c.toDataURL().split(',')[1]});await page.locator('#image-input').setInputFiles({name:'signature.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.waitForSelector('.stamp');await download('test-output/ink-signature.pdf');
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('mobile overflow');await page.screenshot({path:'test-output/ink-mobile.png',fullPage:true});
 await page.locator('#pdf-input').setInputFiles(file);await page.waitForFunction(()=>!document.querySelector('#pen-toggle').disabled);if(await page.locator('#ink path').count())throw Error('new PDF did not reset ink');if(!await page.locator('#download').isDisabled())throw Error('old edits retained');if(errors.length)throw Error(errors.join(';'));console.log('PASS: four rotated/cropped pages, color, width, ink-only download, combined signature download, undo/redo, mobile and document reset.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
