const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');const {PDFDocument,degrees}=require('./dist/vendor/pdf-lib.min.js');
(async()=>{fs.mkdirSync('test-output',{recursive:true});const browser=await chromium.launch({headless:true,channel:"msedge"});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4173');await page.waitForFunction(()=>window.PDFLib);
const doc=await PDFDocument.create();for(const rotation of [0,90,180,270]){const p=doc.addPage([600,800]);p.setCropBox(30,40,530,700);p.setRotation(degrees(rotation));p.drawText('Rotation '+rotation,{x:100,y:500});}const bytes=await doc.save();
await page.locator('#pdf-input').setInputFiles({name:'rotation-test.pdf',mimeType:'application/pdf',buffer:Buffer.from(bytes)});await page.waitForFunction(()=>document.querySelector('#page-label').textContent==='1 / 4'&&!document.querySelector('#image-input').disabled);
const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=180;c.height=60;const x=c.getContext('2d');x.fillStyle='#dd2222';x.fillRect(0,0,180,60);return c.toDataURL('image/png').split(',')[1]});await page.locator('#image-input').setInputFiles({name:'signature.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.waitForSelector('.stamp');
const box=await page.locator('.stamp').boundingBox();await page.mouse.move(box.x+10,box.y+10);await page.mouse.down();await page.mouse.move(box.x+70,box.y+45,{steps:5});await page.mouse.up();const moved=await page.locator('.stamp').boundingBox();if(moved.x<=box.x+30)throw Error('drag failed');
await page.locator('#size').fill('35');await page.locator('#size').dispatchEvent('input');
for(let n=2;n<=4;n++){await page.locator('#next').click();await page.waitForFunction(n=>document.querySelector('#page-label').textContent===n+' / 4'&&!document.querySelector('#add').disabled,n);await page.locator('#add').click();}
const expected=[];for(let n=4;n>=1;n--){expected[n-1]=await page.locator('.stamp').evaluate(el=>({x:parseFloat(el.style.left)/100,y:parseFloat(el.style.top)/100,w:parseFloat(el.style.width)/100,h:parseFloat(el.style.height)/100}));if(n>1){await page.locator('#prev').click();await page.waitForFunction(n=>document.querySelector('#page-label').textContent===(n-1)+' / 4'&&!document.querySelector('#add').disabled,n);}}
const [dl]=await Promise.all([page.waitForEvent('download'),page.locator('#download').click()]);await dl.saveAs('test-output/signed.pdf');const saved=fs.readFileSync('test-output/signed.pdf');if((await PDFDocument.load(saved)).getPageCount()!==4)throw Error('page loss');
const result=await page.evaluate(async({data,expected})=>{const pdfjs=await import('./vendor/pdf.mjs');const pdf=await pdfjs.getDocument({data:new Uint8Array(data)}).promise;const results=[];for(let n=1;n<=4;n++){const p=await pdf.getPage(n),v=p.getViewport({scale:1}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;const ctx=c.getContext('2d');await p.render({canvasContext:ctx,viewport:v}).promise;const pixels=ctx.getImageData(0,0,c.width,c.height).data;let minX=c.width,minY=c.height,maxX=0,maxY=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){const i=(y*c.width+x)*4;if(pixels[i]>170&&pixels[i+1]<80&&pixels[i+2]<80){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);}}const e=expected[n-1];const delta=Math.max(Math.abs(minX-e.x*v.width),Math.abs(minY-e.y*v.height),Math.abs(maxX-(e.x+e.w)*v.width),Math.abs(maxY-(e.y+e.h)*v.height));results.push({page:n,rotation:v.rotation,delta});if(delta>3)throw Error('Export placement mismatch '+JSON.stringify(results));}return results;},{data:[...saved],expected});
await page.screenshot({path:'test-output/desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(400);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('mobile overflow');await page.screenshot({path:'test-output/mobile.png',fullPage:true});
await page.locator('.stamp').focus();await page.keyboard.press('Delete');if(await page.locator('.stamp').count())throw Error('delete failed');await page.locator('#pdf-input').setInputFiles({name:'bad.pdf',mimeType:'application/pdf',buffer:Buffer.from('not a pdf')});await page.waitForFunction(()=>document.querySelector('#status').classList.contains('error'));if(await page.locator('#page-label').textContent()!=='1 / 4')throw Error('bad upload destroyed document');console.log(JSON.stringify({exportChecks:result,mobile:'passed',drag:'passed',delete:'passed',invalidPDF:'passed',pageErrors:errors}));await browser.close();if(errors.length)process.exit(1);})().catch(e=>{console.error(e);process.exit(1)});

